### ISSUE TITLE
bug(docker): docker run not working

### ISSUE THREAD

**Issue by dipankardas011** [lizrice/libbpfgo-beginners#4]
![image](https://user-images.githubusercontent.com/65275144/235218793-408bfb64-4991-4b1b-b044-a2160df18ac9.png)

OS
- fedora 37

**Comment by caboteria** [comment]
Ubuntu 20.10 is no longer supported as it wasn't an LTS release. Changing the FROM line in the Dockerfile to use ubuntu:22.04 (which is an LTS release) worked for me.

https://github.com/lizrice/libbpfgo-beginners/blob/7268f814310b9611950e84033871803e40add8ee/Dockerfile#L1

**Comment by caboteria** [comment]
I submitted a PR with a few Dockerfile updates: https://github.com/lizrice/libbpfgo-beginners/pull/5
